# AUTOGENERATED! DO NOT EDIT! File to edit: ../search.ipynb.

# %% auto 0
__all__ = ['MCTSNode']

# %% ../search.ipynb 3
import numpy as np
import alphazero.go as go

# %% ../search.ipynb 4
class MCTSNode():
    def __init__(self, state, action_probs, valid_actions, branches, value, is_endstate, parent_index, index):
        self.action_probs = action_probs
        self.valid_actions = valid_actions
        self.branches = branches
        self.visits = 0
        self.value = value
        self.path_value = value
        self.is_endstate = is_endstate
        self.parent_index = parent_index
        self.index = index
