# AUTOGENERATED! DO NOT EDIT! File to edit: ../search.ipynb.

# %% auto 0
__all__ = ['MCSTNode', 'MCSTree']

# %% ../search.ipynb 3
import numpy as np
import alphazero.go as go
import torch.nn

# %% ../search.ipynb 5
class MCSTNode():
    """
    Represents a single node in a search tree.
    """
    def __init__(self, 
                 state, # state engine object. Handles scoring, valid actions, turn, etc.
                 action_probs:np.ndarray=None, # probabilities on taking each action. Initially output from a model, can be modified by AlphaZero's MCTS.
                 action_index:int=None, # index into the previous node state's action array leading to the current node. Used to lookup the probability of the action that led to this node.
                 branches:tuple=None, # n_actions-length array containing indices of branch nodes. Branches are reserved indices and do not have to exist in the tree. Node branch indices must be reserved for a 1-1 action-branch node mapping.
                 descendants:list=None, # index array of all nodes descending from current. Used to quickly prune the tree. Descendants must exist in the tree.
                 value:float=None, # action value of the current state
                 parent_index:int=None, # index of parent node
                 index:int=None,): # node index in search tree
        self.state = state
        self.action_probs = action_probs
        self.action_index = action_index
        self.branches = branches
        self.descendants = descendants
        self.visits = 0
        self.value = value
        self.path_value = value
        self.parent_index = parent_index
        self.index = index

    # def update(self):
    #     """
    #     Updates a node's statistics.
    #     """
    #     self.mean_action_value = self.path_value / self.visits
    #     self.exploration_value = self.

# %% ../search.ipynb 7
class MCSTree():
    """
    Monte Carlo Search Tree class. An MCS tree is functionally a dictionary of index:`MCTSNode` pairs, with attendant methods for simulation and maintenance. The MCST binds a model with a state engine.
    """
    def __init__(self, 
                 n_actions:int=None, # number of actions at each turn
                 n_sims:int=1, # number of simulations to run per turn. Tree will expand by this many nodes each turn on average.
                 model:torch.nn.Module=None, # the neural network model which assesses states.
                 noise_ε:float=0.25, # epsilon parameter modifying dirichlet noise function
                 noise_α:float=0.03, # alpha parameter for dirichlet noise function
                 c_puct:float=1.0, # MCTS exploration parameter constant.
                 ):
        self.rng = np.random.default_rng(seed=0)
        self.tree = {}
        self.n_actions = n_actions
        self.model = model
        self.n_sims = n_sims
        self.noise_ε =  noise_ε
        self.noise_α = noise_α
        self.root_idx = 0
        self.next_idx = 1
        self.add_node(None, self.root_idx, go.Position())
        self.c_puct = c_puct
        self.temperature_inv = 1/1.0
        self.moves_played = 0
        self.policy = np.zeros(n_actions)

    def _populate_descendants(self, idx):
        """
        Adds the current node to list of descendants of all ascendant nodes to root.
        """
        parent_idx = self.tree[idx].parent_index
        while parent_idx in self.tree:
            self.tree[parent_idx].descendants.append(idx)
            parent_idx = self.tree[parent_idx].parent_index

    def _build_node(self, state):
        raise NotImplementedError("Method is currently a stub.")

    def _remove_node(self, idx): # NOTE: redundant?
        del self.tree[idx]

    def assess_state(self, state):
        """
        Runs a model to assess a state, and post processes the result. Returns an action value and array of probabilities.
        """
        # run model on state
        if self.model is None:
            value = self.rng.random()
            probs = self.rng.random(size=state.all_legal_moves().size) * state.all_legal_moves()
        else:
            value, probs = self.model(state.board)
        # apply noise: P(s,) = (1 - ε)•p(s,) + ε•η; η=dir(α)
        probs = (1 - self.noise_ε)*probs +  self.noise_ε*self.rng.dirichlet(self.noise_α*np.ones_like(probs))
        return value * state.to_play * -1, probs * state.to_play # state value from perspective of player that led to this state; action value from current player

    def add_node(self,
                 parent_idx, # tree index of parent node
                 idx,        # tree index of node
                 state):     # state engine instance
        state_value,state_probs = self.assess_state(state) # probabilities & values are computed once on node creation
        self.tree[idx] = MCSTNode(state=state,
                    action_probs=state_probs,
                    branches = tuple(i + self.next_idx for i in range(state.all_legal_moves().sum())),
                    descendants = [],
                    value=state_value,
                    parent_index=parent_idx,
                    index=idx)
        self.next_idx += len(self.tree[idx].branches)
        self._populate_descendants(idx)

    def prune(self, idx):
        """
        Removes a node and all its descendants from the search tree. Resets the root node if specified.
        """
        for i in self.tree[idx].descendants: del self.tree[idx]
        del self.tree[idx]

    def set_root_and_prune(self, idx): # NOTE: may need a less ambiguous name for this. too similar to simulation selection (which isn't destructive)
        """
        Sets tree root to selected node, removes previous root, and prunes all nodes not descended from the new root.
        """
        for branch in self.tree[self.root_idx].branches: # remove all subtrees except selected
            if branch != idx: self.prune(idx)
        self._remove_node(self.root_idx)                 # remove root node
        self.root_idx = idx                              # set root node to selected

    def search(self):
        """
        MCTS simulation loop.
        """
        # run simulations
        for i in range(self.n_sims): self.simulate()
        # build policy array
        for i,bdx in enumerate(self.tree[self.root_idx].branches):
            if bdx in self.tree: self.policy[i] += self.tree[bdx].visits
        exposum = self.policy.sum() ** (self.temperature_inv)
        self.policy = np.array([pi**(self.temperature_inv)/exposum for pi in self.policy])
        
        self.moves_played += 1
        if self.moves_played == 30: self.temperature_inv = 1/0.1

        # return selected action
        return np.argmax(self.policy)

    def simulate(self):
        """
        Implements a = argmax(Q(s,a), U(s,a))
        """

        # forloop
        idx = self.root_idx
        parent_idx = self.tree[idx].parent_index
        adx = self.n_actions # default action is pass

        # explore tree until reaching end state or unexplored node
        while idx in self.tree and not self.tree[idx].state.is_game_over():
            self.tree[idx].visits += 1

            # upper confidence bound = mean action value + exploration value; UCB = Q+U
            ucbs = np.zeros(self.n_actions, dtype=np.float32)
            sum_visits = sum(self.tree[bdx].visits for bdx in self.tree[idx].branches if bdx in self.tree)
            for i in range(self.tree[idx].state.all_legal_moves().sum()): # node branch idxs must be reserved for a 1-1 action-branch node mapping
                # build UCB: Q(s,a) + U(s,a)

                bdx = self.tree[idx].branches[i] # branch index
                if bdx in self.tree:
                    mav = self.tree[bdx].path_value / self.tree[bdx].visits
                    exv = self.c_puct * self.tree[idx].action_probs[i] * np.sqrt(sum_visits - self.tree[bdx].visits) / (1 + self.tree[bdx].visits)
                else:
                    mav = exv = 0.0
                ucbs[i] = (mav + exv) * self.tree[idx].state.to_play # action values seen from current player's perspective
            
            # select next action: a = argmax(UCB)
            # omit all invalid moves from consideration via mask
            mask = np.zeros(self.n_actions)
            mask[np.where(self.tree[idx].state.all_legal_moves()==0)] = 1
            adx = np.argmax(np.ma.array(ucbs, mask=mask)).astype(int)
            parent_idx = idx
            idx = self.tree[idx].branches[adx]
            
        # if new state, create node and assess
        if idx not in self.tree:
            coord = go.action_array_index_to_coord(adx) # convert action array index into playable coordinate
            new_state = self.tree[parent_idx].state.play_move(coord)
            self.add_node(parent_idx=parent_idx, idx=idx, state=new_state)
            self.tree[idx].visits += 1

        # propagate action value back down path
        value = self.tree[idx].value
        idx = self.tree[idx].parent_index
        while idx != self.root_idx:
            value *= -1 # sign flip for alternative player turn
            self.tree[idx].path_value += value
            idx = self.tree[idx].parent_index

        # TODO: heavier weighting for win/loss?

